---
title: "Survival - frequentist"
output: html_notebook
---


```{r}
devtools::load_all()
library(tidyverse)
library(survival)

theme_set(cowplot::theme_cowplot())
data <- read_data_for_analysis()
wide <- data$marker_data_wide


hypothesis_res_list <- list()

cache_dir <- here::here("local_temp_data")
if(!dir.exists(cache_dir)) {
  dir.create(cache_dir)
}

```

# Competing risks death vs. discharged


```{r}
data_surv <- wide %>%  
  filter(day > 0) %>%
  mutate(daym1 = day - 1,
    status = fct_collapse(breathing, Hospitalized = breathing_levels) %>% factor(ordered = FALSE) %>% fct_relevel("Hospitalized", "Discharged", "Death") %>% fct_explicit_na("Hospitalized")
  ) %>%
  inner_join(data$patient_data, by = c("hospital_id", "patient_id")) 

f_competing_hcq <- Surv(daym1, day,status) ~ age + sex + took_hcq

#survcheck(f_competing_hcq, data = data_surv, id = patient_id)
fit_competing_hcq <- coxph(f_competing_hcq, data = data_surv, id = patient_id)
fit_competing_hcq

hypothesis_res_list[["competing_hcq"]] <-
  rbind(
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_reduces_death, fit_competing_hcq,
                                        coefficient_name = "took_hcqTRUE", transition = "1:3", adjusted = "age, sex"),
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_increases_discharged, fit_competing_hcq,
                                        coefficient_name = "took_hcqTRUE", transition = "1:2", adjusted = "age, sex")
  )

hypothesis_res_list[["competing_hcq"]]
```

```{r}
f_competing_hcq_az <- update.formula(f_competing_hcq, . ~ . + took_az)
fit_competing_hcq_az <- coxph(f_competing_hcq_az, data = data_surv, id = patient_id)

fit_competing_hcq_az

hypothesis_res_list[["competing_hcq_az"]] <-
  rbind(
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_reduces_death, fit_competing_hcq_az,
                                        coefficient_name = "took_hcqTRUE", transition = "1:3", adjusted = "age, sex, az"),
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_increases_discharged, fit_competing_hcq_az,
                                        coefficient_name = "took_hcqTRUE", transition = "1:2", adjusted = "age, sex, az"),
  frequentist_hypothesis_res_from_coxph(hypotheses$az_reduces_death, fit_competing_hcq_az,
                                        coefficient_name = "took_azTRUE", transition = "1:3", adjusted = "age, sex, hcq"),
  frequentist_hypothesis_res_from_coxph(hypotheses$az_increases_discharged, fit_competing_hcq_az,
                                        coefficient_name = "took_azTRUE", transition = "1:2", adjusted = "age, sex, hcq")
  )
hypothesis_res_list[["competing_hcq_az"]]
```


```{r}
f_competing_hcq_az_fpv <- update.formula(f_competing_hcq_az, . ~ . + took_favipiravir)
fit_competing_hcq_az_fpv <- coxph(f_competing_hcq_az_fpv, data = data_surv, id = patient_id)

fit_competing_hcq_az_fpv

hypothesis_res_list[["competing_hcq_az_fpv"]] <-
  rbind(
  frequentist_hypothesis_res_from_coxph(hypotheses$favipiravir_reduces_death, fit_competing_hcq_az_fpv,
                                        coefficient_name = "took_favipiravirTRUE", transition = "1:3", adjusted = "age, sex, hcq, az", model_check = "Problematic"),
  frequentist_hypothesis_res_from_coxph(hypotheses$favipiravir_increases_discharged, fit_competing_hcq_az_fpv,
                                        coefficient_name = "took_favipiravirTRUE", transition = "1:2", adjusted = "age, sex, hcq, az", model_check = "Problematic")
  )
hypothesis_res_list[["competing_hcq_az_fpv"]]
```

```{r}
f_competing_hcq_az_admitted <- update.formula(f_competing_hcq_az, . ~ . + admitted_for_covid)
fit_competing_hcq_az_admitted <- coxph(f_competing_hcq_az_admitted, data = data_surv, id = patient_id)

fit_competing_hcq_az_admitted

hypothesis_res_list[["competing_hcq_az_admitted"]] <-
  rbind(
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_reduces_death, fit_competing_hcq_az_admitted,
                                        coefficient_name = "took_hcqTRUE", transition = "1:3", adjusted = "age, sex, admitted, az"),
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_increases_discharged, fit_competing_hcq_az_admitted,
                                        coefficient_name = "took_hcqTRUE", transition = "1:2", adjusted = "age, sex, admitted, az"),
  frequentist_hypothesis_res_from_coxph(hypotheses$az_reduces_death, fit_competing_hcq_az_admitted,
                                        coefficient_name = "took_azTRUE", transition = "1:3", adjusted = "age, sex, admitted, hcq"),
  frequentist_hypothesis_res_from_coxph(hypotheses$az_increases_discharged, fit_competing_hcq_az_admitted,
                                        coefficient_name = "took_azTRUE", transition = "1:2", adjusted = "age, sex, admitted, hcq")
  )
hypothesis_res_list[["competing_hcq_az_admitted"]]
```

```{r}
f_competing_hcq_az_hospital <- update.formula(f_competing_hcq_az, . ~ . + hospital_id)
data_surv_hospital <- data_surv %>% 
  mutate(hospital_id = if_else(hospital_id %in% c("DJkhZ", "lRBHa", "nDINR"), "small", hospital_id))
fit_competing_hcq_az_hospital <- coxph(f_competing_hcq_az_hospital, data = data_surv_hospital, id = patient_id)
fit_competing_hcq_az_hospital

hypothesis_res_list[["competing_hcq_az_hospital"]] <-
  rbind(
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_reduces_death, fit_competing_hcq_az_hospital,
                                        coefficient_name = "took_hcqTRUE", transition = "1:3", adjusted = "age, sex, az, hospital"),
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_increases_discharged, fit_competing_hcq_az_hospital,
                                        coefficient_name = "took_hcqTRUE", transition = "1:2", adjusted = "age, sex, az, hospital"),
  frequentist_hypothesis_res_from_coxph(hypotheses$az_reduces_death, fit_competing_hcq_az_hospital,
                                        coefficient_name = "took_azTRUE", transition = "1:3", adjusted = "age, sex, hcq, hospital"),
  frequentist_hypothesis_res_from_coxph(hypotheses$az_increases_discharged, fit_competing_hcq_az_hospital,
                                        coefficient_name = "took_azTRUE", transition = "1:2", adjusted = "age, sex, hcq, hospital")
  )
hypothesis_res_list[["competing_hcq_az_hospital"]]

```


```{r}
f_competing_hcq_az_comorbidities_sum <- update.formula(f_competing_hcq_az, . ~ . + comorbidities_sum)
fit_competing_hcq_az_comorbidities_sum <- coxph(f_competing_hcq_az_comorbidities_sum, data = data_surv, id = patient_id)
fit_competing_hcq_az_comorbidities_sum

hypothesis_res_list[["competing_hcq_az_comorbidities_sum"]] <-
  rbind(
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_reduces_death, fit_competing_hcq_az_comorbidities_sum,
                                        coefficient_name = "took_hcqTRUE", transition = "1:3", adjusted = "age, sex, az, comorbidities (sum)"),
  frequentist_hypothesis_res_from_coxph(hypotheses$hcq_increases_discharged, fit_competing_hcq_az_comorbidities_sum,
                                        coefficient_name = "took_hcqTRUE", transition = "1:2", adjusted = "age, sex, az, comorbidities (sum)")
  )
hypothesis_res_list[["competing_hcq_az_comorbidities_sum"]]
```





# Peak IL-6, peak D-dimer


```{r}
f_competing_marker_base <- Surv(daym1, day,status) ~ age + sex
f_competing_il_6 <- update.formula(f_competing_marker_base, . ~ . + log_peak_IL_6)

data_IL_6 <- data_surv %>%
  group_by(patient_id) %>%
  filter(any(!is.na(IL_6))) %>%
  ungroup() %>%
  compute_marker_peak(column_name = "IL_6", new_column_name = "peak_IL_6", initial_value = 1) %>%
  mutate(log_peak_IL_6 = log(peak_IL_6))


fit_competing_il_6 <- coxph(f_competing_il_6, data = data_IL_6, id = patient_id, control = coxph.control(iter.max = 200))
fit_competing_il_6

hypothesis_res_list[["competing_il_6"]] <-
  frequentist_hypothesis_res_from_coxph(hypotheses$IL_6_increases_death, fit_competing_il_6,
                                        coefficient_name = "log_peak_IL_6", transition = "1:3", adjusted = "age, sex", model_check = "Suspicious")
hypothesis_res_list[["competing_il_6"]]
```
```{r}
f_competing_d_dimer <- update.formula(f_competing_marker_base, . ~ . + log_peak_d_dimer)

data_d_dimer <- data_surv %>%
  group_by(patient_id) %>%
  filter(any(!is.na(d_dimer))) %>%
  ungroup() %>%
  compute_marker_peak(column_name = "d_dimer", new_column_name = "peak_d_dimer", initial_value = 0) %>%
  mutate(log_peak_d_dimer = log(peak_d_dimer + 1) - 4)


fit_competing_d_dimer <- coxph(f_competing_d_dimer, data = data_d_dimer, id = patient_id, control = coxph.control(iter.max = 2000))
fit_competing_d_dimer

hypothesis_res_list[["competing_d_dimer"]] <-
  frequentist_hypothesis_res_from_coxph(hypotheses$d_dimer_increases_death, fit_competing_d_dimer,
                                        coefficient_name = "log_peak_d_dimer", transition = "1:3", adjusted = "age, sex", model_check = "Problematic")
hypothesis_res_list[["competing_d_dimer"]]
```


```{r}
hypothesis_res_all <- do.call(rbind, hypothesis_res_list)
write_csv(hypothesis_res_all, path = here::here("manuscript", "/competing_risks_res.csv"))
```
