---
title: "Detailed disease progression of 88 patients hospitalized with Covid-19 in the Czech Republic: A dataset and exploratory analysis" 
output: pdf_document
abstract: "We collected a multi-centric retrospective dataset of patients who were admitted to 10 hospitals in Czech Republic and tested positive for SARS-CoV-2. The dataset contains baseline patient characteristics, breathing support required, pharmacological treatment received and multiple markers on daily resolution. To assess association between treatments, markers and patient outcomes we performed multiverse analysis, observing how the conclusions change between defensible choices of statistical model, predictors included in the model and other analytical degrees of freedom."
bibliography: Covid19.json
---


```
{r setup}
devtools::load_all()
library(tidyverse)
theme_set(cowplot::theme_cowplot())
data <- read_data_for_analysis()
```

# Introduction 

The Covid-19 pandemic, caused by severe acute respiratory syndrome coronavirus (SARS-CoV-2) has, as of September 2020 led to over 28 million cases and over 900 000 deaths. Proposed treatments include antivirals approved for other indications (Chloroquine, Hydroxychloroquine, Lopinavir/Ritonavir, Remdesivir, Favipiravir, Umifenovir), Azithromycin, corticosteriods, immunoglobulins, Tocilizumab and convalescent plasma [@http://zotero.org/users/5567156/items/8XWTUMUI; @http://zotero.org/users/5567156/items/6Q8Z8VJR; TODO]. Currently, the only treatment that exhibited positive effects in randomized trials is the corticosteriod Dexamethasone for severe cases [@http://zotero.org/users/5567156/items/IW6VZ53Q; http://zotero.org/users/5567156/items/5VAKEW58]. While initially promising, Hydroxychloroquine has failed to show benefit for both hospitalized patients [@http://zotero.org/users/5567156/items/9X3UH8ZM], as early treatment [@https://www.acpjournals.org/doi/10.7326/M20-4207] and as post-exposure profylaxis [@http://zotero.org/users/5567156/items/7C23YCV5; http://zotero.org/users/5567156/items/GMR9FX9Z]. Further, no improvement could be discerned when adding Azithromycin to Hydroxychloroquine therapy [@http://zotero.org/users/5567156/items/BQLRZGTQ]. Similarly, Lopinavir/Ritonavir also did not show benefit [@http://zotero.org/users/5567156/items/6I6GAVWU]. No benefit was observed for convalscent plasma [@http://zotero.org/users/5567156/items/UEXLDJCB; http://zotero.org/users/5567156/items/BHGT88US] For additional summary see (live review)   

In observational studies, Hydroxychloroquine was often found to be associated with better outcomes [e. g., @http://zotero.org/users/5567156/items/WZPNBRYN; http://zotero.org/users/5567156/items/4HR7MUJ6; http://zotero.org/users/5567156/items/NXC9CDI9]

High IL-6, D-dimer values were observed to be associated with outcome and disease severity [@http://zotero.org/users/5567156/items/ID7F3XIH].
Large study of electronic health records [@http://zotero.org/users/5567156/items/ARTB8HYZ] showed TODO.

An ongoing challenge in evalutating Covid-19 treatments is that the analysis and interpretation of the data is often inappropriate or misleading, most notably interpreting lack of evidence due to small sample size as evidence of no effect [see e.g., @http://zotero.org/users/5567156/items/5PZEEPJV; @http://zotero.org/users/5567156/items/AZDZHLJV].



# Methods

A convenience sample of patients... The study was approved by the Ethical committees of TODO.

Sex differences are to be expected for both sociological and biological [@http://zotero.org/users/5567156/items/5KQZ3XEE] reasons.

Important to consider appropriate estimands [@http://zotero.org/users/5567156/items/MH797GNC].

We performed multiverse analysis [@http://zotero.org/users/5567156/items/DXWM259V]

# Results

```
{r}
n_patients <- nrow(data$patient_data)
n_hospitals <- length(unique(data$patient_data$hospital_id))
```


# References
