---
title: "Supplementary figures for Detailed disease progression of 213 patients hospitalized with Covid-19 in the Czech Republic: An exploratory analysis" 
output: 
  #rticles::arxiv_article
  # bookdown::pdf_document2:
  #    toc: false
  bookdown::word_document2: 
    toc: false
    reference_docx: "output_template.docx"
#date: "Version: `r format(Sys.time(), '%Y-%m-%d')`"
---

```{r setup, echo=FALSE, message=FALSE, warning = FALSE, results = "hide"}
knitr::opts_chunk$set(echo = FALSE, fig.width = 8, cache = TRUE)

devtools::load_all()
library(tidyverse)
library(patchwork)
library(tsiMisc) # devtools::install_github("tsieger/tsiMisc")
library(UpSetR)

theme_set(cowplot::theme_cowplot())
data <- read_data_for_analysis()
wide <- data$marker_data_wide

```


```{r datacollectionperiod, fig.height=2.5, fig.cap= "Data collection periods at individual sites, showing the range of admission dates of patients included in the study. Note that we cannot provide additional information to link the sites here with data shown elsewhere as that would  increase the risk of deanonymization of the patients."}
data_collection_period <- read_csv(here::here("manuscript", "data_collection_period.csv"), col_types = cols(
  first_admission = col_date(format = "%Y-%m-%d"),
  last_admission = col_date(format = "%Y-%m-%d"),
  hospital_id_anon = col_integer()
))

s1_fig <- data_collection_period %>% ggplot(aes(xmin = first_admission, xmax = last_admission, y = hospital_id_anon)) + geom_linerange(size = 3) + scale_y_continuous("Study site")+
  scale_x_date("Data collection period", date_breaks = "2 weeks")  + theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)  )

s1_fig
ggsave(s1_fig, filename = "supp_figs_production/S1_fig.tiff", width = 7.5, height = 2.5 * (7.5/8))
```


```{r upsettreatment, fig.cap = "Upset plot of treatment combinations - each vertical bar displays the number of patients that received the combination indicated by filled dots in the matrix. Horizontal bars show the total number of patients receiveing the given treatment.", fig.width=8, fig.height=5.8 }
upset_data <- data$patient_data %>% select(starts_with("ever")) %>% mutate(across(starts_with("ever"), as.integer)) %>% as.data.frame()

names(upset_data) <- gsub("ever_", "", names(upset_data)) %>% gsub("_", " ", .) %>% gsub("hcq", "hydroxychloroquine", .) %>% gsub("az", "azithromycin", .)

names(upset_data) <- paste0(toupper(substring(names(upset_data),1,1)), substring(names(upset_data),2))

s2_fig <- UpSetR::upset(upset_data, sets = names(upset_data), text.scale = 2)
s2_fig
tiff(filename = "supp_figs_production/S2_fig.tiff", width = 7.5, height = 5.8 * (7.5/8), units = "in", res = 300)
s2_fig
dev.off()
```



```{r outcome_by_hospital_prepare, echo=FALSE}
tmp<-data$patient_data[,c('patient_id','hospital_id','outcome')]
tmp$outcome[tmp$outcome=='Transferred']<-'Hospitalized'
tmp$outcome<-dropLevels(tmp$outcome)
tmp$hospital_id<-factor(tmp$hospital_id)
levels(tmp$hospital_id)<-paste('H',1:length(levels(tmp$hospital_id)),sep='')
```


```{r outcomebyhospital, echo=FALSE}
# knitr::kable(with(tmp,table(outcome,hospital_id)),caption = paste0( "Overview of outcomes in different hospitals. Note that at H6, 9 out of 19 patients died, while at H9, no patient died out of 9 patients treated. There were large differences between hospitals in the ratio of fatal outcomes (P=", round(fisher.test(with(tmp,table(outcome,hospital_id)),simulate.p.value=T)$p.value,5), ")"), booktabs = TRUE)
```

```{r hospitaloutcomes,fig.cap="Number of patients and outcomes at the individual sites. The numbers above bars are the exact counts. Hospitalized = still hospitalized at the end of data collection at the site or transferred to other site and lost to followup. Sites are anonymized to preserve patient privacy.", fig.height=3.5}
s3_fig <- data$patient_data %>% mutate(
  hospital_label = factor(paste0("H", as.integer(factor(hospital_id))), levels = paste0("H", 1:10)),
  outcome = fct_collapse(outcome, Hospitalized = c("Hospitalized", "Transferred")) %>% fct_relevel("Death", "Hospitalized", "Discharged")
) %>%
  ggplot(aes(x = hospital_label,  fill = outcome)) + geom_bar(position = position_dodge()) + 
  geom_text(stat='count', aes(label=..count..), vjust=-1, position = position_dodge(width = 1)) +
  #scale_fill_viridis_d("Outcome") +
  scale_fill_manual("Outcome", values = c(Death = as.character(bfc()["Black"]), Hospitalized = as.character(bfc()["Bluish green"]), Discharged = as.character(bfc()["Yellow"]))) +
  scale_x_discrete("Study site") +
  scale_y_continuous("Count") +
  expand_limits(y = 36)

s3_fig
ggsave(s3_fig, filename = "supp_figs_production/S3_fig.tiff", width = 7.5, height = 3.5 * (7.5/8))
```

```{r markeroverlaps, fig.cap = "Density plots of worst marker values per patient, stratified by worst condition experienced by the patient. For each patient that had a given marker measured, the worst value was taken. Additionally the patients are classified by the worst condition (regardless of the timing relative to the worst marker levels). For each set of patients and marker an empirical density plot of the worst marker values is shown.", fig.height=6}
frac <- 0.2
s4_fig <- data$marker_data %>% filter(marker %in% c("lymphocyte_count", "d_dimer", "CRP", "IL_6")) %>%
  inner_join(data$patient_data, by = c("hospital_id", "patient_id")) %>%
  #filter(worst_breathing %in% c("AA", "Death")) %>%
  group_by(marker, patient_id, worst_breathing_s) %>%
  summarise(worst_value = case_when(marker == "lymphocyte_count" ~ min(log10(value)),
                                    marker == "IL_6" ~ max(log10(value)),
                                    TRUE ~ max(value)),
            .groups = "drop") %>% 
  filter(!is.infinite(worst_value)) %>%
  mutate(marker = factor(marker, levels = c("lymphocyte_count", "d_dimer", "CRP", "IL_6"),
         labels = c("Lowest Log10(lymphocyte count)", "Highest D-dimer", "Highest CRP", "Highest Log10(IL_6)"))) %>%
  ggplot(aes(x = worst_value, color = worst_breathing_s, fill = worst_breathing_s, group = worst_breathing_s)) +
  geom_density(adjust = 2, alpha = 0.3) +
  scale_color_viridis_d("Worst condition") +
  scale_fill_viridis_d("Worst condition") +
  scale_x_continuous("Marker value") +
  facet_wrap(~marker, scales = "free", ncol = 1)

s4_fig
ggsave(s4_fig, filename = "supp_figs_production/S4_fig.tiff", width = 7.5, height = 6 * (7.5/8))
#Validating the claim about overlapping proportions
# frac <- 0.2
# data$marker_data %>% filter(marker %in% c("lymphocyte_count", "d_dimer", "CRP")) %>%
#   inner_join(data$patient_data, by = c("hospital_id", "patient_id")) %>%
#   filter(worst_breathing_s != "Oxygen") %>%
#   mutate(worst_breathing_s = fct_collapse(worst_breathing_s, "Ventilated or Death" = c("Ventilated", "Death"))) %>%
#   group_by(marker, patient_id, worst_breathing_s) %>%
#   summarise(min_value = min(value), max_value = max(value), .groups = "drop") %>%
#   group_by(marker, worst_breathing_s) %>%
#   summarise(qlowmin = quantile(min_value, frac), qhigh_min = quantile(min_value, 1 - frac), qlow_max = quantile(max_value, frac), qhigh_max = quantile(max_value, 1 - frac), .groups = "drop")

```
```{r}
# data$marker_data %>% 
#   filter(marker %in% c("lymphocyte_count", "CRP", "d_dimer","IL_6"), value > 0, day >=0) %>%
#   inner_join(data$breathing_data, by = c("hospital_id", "patient_id", "day")) %>%
#   filter(breathing_s != "Death") %>%
#   ggplot(aes(x = day, y = value, color = breathing_s, group = patient_id)) +
#     geom_line(alpha = 0.8, position = position_jitter(width = 0.2, height = 0)) +
#    # geom_point(, alpha = 0.5, position = position_jitter(width = 0.2, height = 0)) +
#   scale_y_log10() + 
#   scale_color_manual("Breathing", values = c(Ventilated = as.character(bfc()["Black"]), Oxygen = as.character(bfc()["Bluish green"]), AA = as.character(bfc()["Orange"]))) + #scale_color_brewer(type = "qual") +
#   # scale_color_viridis_d(guide = guide_legend(override.aes = list(alpha = 1)), direction = -1, end = 0.9) +
#   facet_wrap(~marker, scales = "free_y")
#   
```


```{r initiation, fig.cap="Histogram of timing of first treatment relative to admission into one of the study sites. Two patients initiated treatment before admission, which is shown as the negative numbers.", fig.height=2}
#data$marker_data %>% filter(marker == "favipiravir") %>% group_by(patient_id) %>% summarise(days = n(), .groups = "drop") %>% summarise(min_days = min(days), max_days = max(days))
#data$marker_data %>% filter(marker == "az") %>% group_by(patient_id) %>% summarise(days = sum(!is.na(value) & value > 0), .groups = "drop") %>% filter(days > 0) %>% ggplot(aes(x = days)) + geom_histogram(binwidth = 1)
#data$marker_data%>% filter(marker == "az") %>% group_by(value) %>% summarise(n())

#Patients treated with convalescent plasma received 1-3 units of plasma over 1-2 days.

marker_map <- c("hcq" = "Hydroxychloroquine", "az" = "Azithromycin", "favipiravir" = "Favipiravir", "convalescent_plasma" = "Conv. plasma")

s5_fig <- data$marker_data %>% 
  filter(marker %in% c("az", "hcq", "favipiravir"), !is.na(value), value > 0) %>%
  mutate(marker = factor(marker_map[marker], levels = marker_map)) %>%
  group_by(marker, patient_id) %>% 
  summarise(first_day = min(day), .groups = "drop") %>% 
  ggplot(aes(x = first_day)) + geom_histogram(binwidth = 1) + facet_wrap(~marker, scales = "free_y", nrow = 1) + scale_x_continuous("First day of treatment relative to admission")

s5_fig
ggsave(s5_fig, filename = "supp_figs_production/S5_fig.tiff", width = 7.5, height = 2 * (7.5/8))
```


```{r allmulthcq, fig.height=11, fig.cap = "Estimates of model coefficients for association between hydroxychloroquine and main outcomes. The \"Suspicious\" section shows models that were found to not fit the data well or have computational issues - see supplementary statistical analysis for details.  Each row represents a model - Categorical All/7/28 = Bayesian categorical regression for state at last observed day/day 7/day 28, Binary All/7/28 = Bayesian logistic regression for state at last observed day/day 7/day 28, Bayes Cox = Bayesian version of the Cox proportional hazards model with a binary outcome, Cox (single) = frequentist Cox model with a binary outcome, Cox (competing) = frequentist Cox model using competing risks (as in Figure 1a), HMM A = Bayesian hidden-Markov model as in Figure 1b with predictors for rate groups, HMM B = Bayesian hidden-markov model as in Figure 1b with predictors for individual rates, HMM C = Bayesian hidden-Markov model as in Figure 1c. For frequentist models, we show maximum likelihood estimate and 95% confidence interval, for Bayesian models we show posterior mean and 95% credible interval. The estimands are either log odds-ratio (Categorical, HMM) or log hazard ratio (Cox variants) or log ratio of mean duration of hospitalization (HMM duration). In all cases coefficient < 0 means better patient outcome in the treatment group. Vertical lines indicate zero (blue) and substantial increase or decrease with odds or hazard ratio of 3:2 or 2:3 (green). Additionally the factors the model adjusted for are listed - Site = the study site, admitted = Admitted for Covid-19, Supportive = best supportive care initiated, Comorb. = total number of comorbidities, AZ = took azithromycin, HCQ = took hydroxychloroquine, FPV = took favipiravir, C. plasma = received convalescent plasma, first wave = only patients admitted before September 1st were included. "}
s6_fig <- plot_multiverse(read_all_multiverse_res() %>% filter(grepl("hcq", hypothesis)), show_check = TRUE)
s6_fig
ggsave(s6_fig, filename = "supp_figs_production/S6_fig.tiff", width = 7.5, height = 11 * (7.5/8))
```


```{r allmultaz, fig.height=11, fig.cap = "Estimates of model coefficients for association between azithromycin and main outcomes. The \"Suspicious\" section shows models that were found to not fit the data well or have computational issues - see supplementary statistical analysis for details.  Each row represents a model - Categorical All/7/28 = Bayesian categorical regression for state at last observed day/day 7/day 28, Binary All/7/28 = Bayesian logistic regression for state at last observed day/day 7/day 28, Bayes Cox = Bayesian version of the Cox proportional hazards model with a binary outcome, Cox (single) = frequentist Cox model with a binary outcome, Cox (competing) = frequentist Cox model using competing risks (as in Figure 1a), HMM A = Bayesian hidden-Markov model as in Figure 1b with predictors for rate groups, HMM B = Bayesian hidden-markov model as in Figure 1b with predictors for individual rates, HMM C = Bayesian hidden-Markov model as in Figure 1c. For frequentist models, we show maximum likelihood estimate and 95% confidence interval, for Bayesian models we show posterior mean and 95% credible interval. The estimands are either log odds-ratio (Categorical, HMM) or log hazard ratio (Cox variants) or log ratio of mean duration of hospitalization (HMM duration). In all cases coefficient < 0 means better patient outcome in the treatment group. Vertical lines indicate zero (blue) and substantial increase or decrease with odds or hazard ratio of 3:2 or 2:3 (green). Additionally the factors the model adjusted for are listed - Site = the study site, admitted = Admitted for Covid-19, Supportive = best supportive care initiated, Comorb. = total number of comorbidities, AZ = took azithromycin, HCQ = took hydroxychloroquine, FPV = took favipiravir, C. plasma = received convalescent plasma, first wave = only patients admitted before September 1st were included. "}
s7_fig <- plot_multiverse(read_all_multiverse_res() %>% filter(grepl("az", hypothesis)), show_check = TRUE)
s7_fig
ggsave(s7_fig, filename = "supp_figs_production/S7_fig.tiff", width = 7.5, height = 11 * (7.5/8))
```


```{r allmultfpv, fig.height=11, fig.cap = "Estimates of model coefficients for association between favipiravir and main outcomes. The \"Suspicious\" section shows models that were found to not fit the data well or have computational issues - see supplementary statistical analysis for details.  Each row represents a model - Categorical All/7/28 = Bayesian categorical regression for state at last observed day/day 7/day 28, Binary All/7/28 = Bayesian logistic regression for state at last observed day/day 7/day 28, Bayes Cox = Bayesian version of the Cox proportional hazards model with a binary outcome, Cox (single) = frequentist Cox model with a binary outcome, Cox (competing) = frequentist Cox model using competing risks (as in Figure 1a), HMM A = Bayesian hidden-Markov model as in Figure 1b with predictors for rate groups, HMM B = Bayesian hidden-markov model as in Figure 1b with predictors for individual rates, HMM C = Bayesian hidden-Markov model as in Figure 1c. For frequentist models, we show maximum likelihood estimate and 95% confidence interval, for Bayesian models we show posterior mean and 95% credible interval. The estimands are either log odds-ratio (Categorical, HMM) or log hazard ratio (Cox variants) or log ratio of mean duration of hospitalization (HMM duration). In all cases coefficient < 0 means better patient outcome in the treatment group. Vertical lines indicate zero (blue) and substantial increase or decrease with odds or hazard ratio of 3:2 or 2:3 (green). Additionally the factors the model adjusted for are listed - Site = the study site, admitted = Admitted for Covid-19, Supportive = best supportive care initiated, Comorb. = total number of comorbidities, AZ = took azithromycin, HCQ = took hydroxychloroquine, FPV = took favipiravir, C. plasma = received convalescent plasma, first wave = only patients admitted before September 1st were included. "}
s8_fig <- plot_multiverse(read_all_multiverse_res() %>% filter(grepl("favipiravir", hypothesis), model_check != "Problematic"), show_check = TRUE)
s8_fig
ggsave(s8_fig, filename = "supp_figs_production/S8_fig.tiff", width = 7.5, height = 11 * (7.5/8))
```

```{r multiverseresultsmarkers, fig.height=5, fig.width=8.5, fig.cap="Estimates of model coefficients (log hazard ratios) for association between markers and death. The \"Suspicious\" section shows models that were found to not fit the data well or have computational issues, \"Problematic\" section shows models that were completely broken - see supplementary statistical analysis for details. Each row represents a model - Cox (competing) =  frequentist Cox model using competing risks (as in Figure 1a), HMM A = Bayesian hidden-markov model as in Figure 1b with predictors for rate groups, JM = Bayesian joint longitudinal and time-to-event model. For frequentist models, we show maximum likelihood estimate and 95% confidence interval, for Bayesian models we show posterior mean and 95% credible interval. Additionally the factors the model adjusted for are listed - Site = the study site, Supportive = best supportive care initiated, HCQ = took Hydroxychloroquine. We show posterior mean and 95% credible interval."}
s9_fig <- plot_multiverse(read_all_multiverse_res() %>% filter(group == "markers"), adjustments_to_hide = c("admitted", "smoking", "obesity", "comorbidities \\(sum\\)", "az", "favipiravir", "convalescent_plasma"), show_check = TRUE)


s9_fig
ggsave(s9_fig, filename = "supp_figs_production/S9_fig.tiff", width = 8.5, height = 5)
```
