---
title: "HMM Model development"
output: html_notebook
---


```{r setup}
library(rstan)
library(tidyverse)
library(cowplot)
theme_set(theme_cowplot())

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

devtools::load_all()
```


```{r}
data <- hmm_simulator(10, 20, 4, use_noisy_states = TRUE)

improving_data <- data.frame(day = data$observed$serie_data$.time, patient = data$observed$serie_data$.serie, improving = data$true$true_improving) %>% filter(improving)

data.frame(day = data$observed$serie_data$.time, patient = data$observed$serie_data$.serie, breathing = data$true$true_base_states) %>%
  mutate(breathing = factor(breathing, 1:nrow(data$observed$observed_state_data), ordered = TRUE)) %>%
  ggplot(aes(x = day, y = patient, fill = breathing)) + geom_tile(width = 1, height = 0.5) + geom_tile(data = improving_data, width = 1, height = 0.1, fill = "gray") + ggtitle("True - gray lines for improving")


data.frame(day = data$observed$serie_data$.time, patient = data$observed$serie_data$.serie, breathing = data$observed$serie_data$.observed) %>%
  mutate(breathing = factor(breathing, 1:nrow(data$observed$observed_state_data), ordered = TRUE)) %>%
  ggplot(aes(x = day, y = patient, fill = breathing)) + geom_tile(width = 1, height = 0.5) + ggtitle("Observed")
```


```{r}
adapt_delta <- 0.9

data <- hmm_simulator(5, 10, 2, use_noisy_states = TRUE)

single_code <- make_stancode_hmm(data$observed)

model_single <- stan_model(model_code = single_code)


standata <- make_standata_hmm(data$observed)


if(inherits(model_single, "stanmodel")) {
  fit <- sampling(model_single, data = standata, control = list(adapt_delta = adapt_delta))
} else {
  cmdstan_fit <- model_single$sample(data = standata, adapt_delta = adapt_delta)
  fit <- rstan::read_stan_csv(cmdstan_fit$output_files())
}
evaluation_summary(fit, data$true)

```

```{r}
data <- hmm_simulator(20, 15, 2, use_noisy_states = TRUE, N_treatments = 0)


bfit <- brmhmm(data$observed)

summary(bfit)


bfit$brmsfit$fit
```


```{r}
#xx <- brms::posterior_epred(bfit) %>% hidden_to_corresponding_observed(bfit$data_processed, .)
xx <- brms::posterior_predict(bfit)


xy <- prediction_to_wide_format(bfit$data, xx)


step_size <- 6
for(step in 1:ceiling(bfit$data_processed$standata$N_series / step_size)) {
  series_id <- ((step - 1) * step_size + 1) : (step* step_size)
  
  posterior_state_plot(xy, series_id, bfit$data) %>% print()

}
```


```{r}
noisy_states_in_sbc <- TRUE
sbc_generator <- function() {
  data <- hmm_simulator(40, 25, 2, use_noisy_states = noisy_states_in_sbc)
  standata <- make_standata_hmm(data$observed)

  list(observed = standata,
       true = data$true,
       observed_raw = data$observed)
}

model_sbc <-  stan_model(model_code = make_stancode_hmm(sbc_generator()$observed_raw))

sbc_res <- sbc(model_sbc, generator = sbc_generator, N_steps = 50, control = list(adapt_delta = adapt_delta))

saveRDS(sbc_res, "sbc.rds")

sbc_res$params %>% filter(grepl("b|sd", param_name)) %>% plot_sbc_params()
sbc_res$params %>% filter(grepl("r_1", param_name)) %>% plot_sbc_params()
sbc_res$params %>% filter(grepl("r_2", param_name)) %>% plot_sbc_params()
if(noisy_states_in_sbc) {
  sbc_res$params %>% filter(grepl("sensitivity", param_name)) %>% plot_sbc_params()
  sbc_res$params %>% filter(grepl("other_observations_probs", param_name)) %>% plot_sbc_params()
}

#sbc_res$params %>% plot_sbc_params()
summarise_sbc_diagnostics(sbc_res)
sbc_res$diagnostics

```



## Apply to Grein et al. dataset

```{r}

disease_levels <- c("AA", "LoO2", "HiO2", "NIPPV", "MV", "ECMO")
breathing_levels <- c("Discharge", disease_levels, "Death")

data_grein <- readxl::read_excel(here::here("public_data", "Grein_et_al.xlsx"), na = c("")) %>%
  select(-Remdesivir_Last_Day) %>%
  pivot_longer(starts_with("Day_"), names_prefix = "Day_", names_to = "day", values_to = "breathing") %>%
  filter(!is.na(breathing)) %>%
  transmute(
    patient = Patient,
    breathing = breathing,
    day = as.integer(day)) %>%
  group_by(patient) %>%
  mutate(breathing_imputed = if_else(breathing == "ND", breathing[which.max(day[breathing %in% c("AA", "LoO2", "HiO2", "NIPPV", "MV", "ECMO")])], breathing)) %>%
  ungroup() %>%
  mutate(
    breathing = factor(breathing, levels = breathing_levels, ordered = TRUE),
    breathing_imputed = factor(breathing, levels = breathing_levels, ordered = TRUE)
  )


```


```{r}

series_data <- data_grein %>% transmute(.serie = as.integer(patient), .time = day + 1, .observed = breathing)

hidden_state_data <- data.frame(id = factor(breathing_levels, levels = breathing_levels)) %>% mutate( corresponding_obs = id)

rate_data <- rbind(
  data.frame(.from = disease_levels, .to = "Death", rate_group = "death"),
  data.frame(.from = "AA", .to = "Discharge", rate_group = "improve_one"),
  data.frame(.from = disease_levels[2 : length(disease_levels)], .to = disease_levels[1 : (length(disease_levels) - 1)], rate_group = "improve_one"),
  data.frame(.from = disease_levels[1 : (length(disease_levels) - 1)], .to = disease_levels[2 : length(disease_levels)], rate_group = "worsen_one")
) %>%
  mutate(.from = factor(.from, levels = breathing_levels),
         .to = factor(.to, levels = breathing_levels),
         )

initial_states <- series_data %>% filter(.time == 1) %>% arrange(.serie) %>% pull(.observed)

prior = brms::set_prior("normal(-2, 5)", "Intercept") +
  brms::set_prior("normal(0, 3)", "b") +
  brms::set_prior("normal(0, 1)", "sd", group = ".rate_id")

grein_hmm <- brmshmmdata(~ rate_group + (1|.rate_id), series_data, rate_data, hidden_state_data, initial_states, prior = prior)

fit_grein <- brmhmm(grein_hmm)

```


```{r}
# fit_grein$data <- grein_hmm
# fit_grein$data_processed <- make_data_hmm(grein_hmm)

#posterior_grein <- brms::posterior_epred(fit_grein)
posterior_grein <- brms::posterior_predict(fit_grein)


posterior_grein_wide <- prediction_to_wide_format(fit_grein$data, posterior_grein)

posterior_grein_wide <- posterior_grein_wide %>% mutate(.predicted = factor(.predicted, levels = 1:length(levels(fit_grein$data$serie_data$.observed)), ordered = TRUE, labels = levels(fit_grein$data$serie_data$.observed)))

step_size <- 6
for(step in 1:ceiling(fit_grein$data_processed$standata$N_series / step_size)) {
  series_id <- ((step - 1) * step_size + 1) : (step* step_size)
  
  posterior_state_plot(posterior_grein_wide, series_id, fit_grein$data) %>% print()

}

#TODO ppchecks: last state, pairwise state transitions, step up/down

```

```{r}
d1 <- data.frame(x = 1, y = factor(1:3, levels = 1:3, labels = c("First","After first","After after first"), ordered = TRUE), f = c(0.1,0.2,0.3))

d2 <- data.frame(x = c(1,2), y2 = factor(c(2,3), levels = 1:3, labels = c("First","After first","After after first"), ordered = TRUE), f = 0.5)

ggplot(d1, aes(x = x, y = y, fill = f)) + geom_raster() + 
  geom_line(data = d2, inherit.aes = FALSE, aes(x = x, y = y2, group = 1))

```

