// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcppeigen_outerproduct
Eigen::MatrixXd rcppeigen_outerproduct(const Eigen::VectorXd& x);
RcppExport SEXP _covid19retrospective_rcppeigen_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppeigen_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// posterior_epred_state_prob_internal
Eigen::VectorXd posterior_epred_state_prob_internal(int n_samples, const Eigen::VectorXi& max_times, const Eigen::VectorXi& initial_states, int n_states, int n_time, int n_predictor_sets, const Eigen::VectorXd& transition_matrices, const Eigen::MatrixXi& predictor_sets_rect);
RcppExport SEXP _covid19retrospective_posterior_epred_state_prob_internal(SEXP n_samplesSEXP, SEXP max_timesSEXP, SEXP initial_statesSEXP, SEXP n_statesSEXP, SEXP n_timeSEXP, SEXP n_predictor_setsSEXP, SEXP transition_matricesSEXP, SEXP predictor_sets_rectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type max_times(max_timesSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type initial_states(initial_statesSEXP);
    Rcpp::traits::input_parameter< int >::type n_states(n_statesSEXP);
    Rcpp::traits::input_parameter< int >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_predictor_sets(n_predictor_setsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type transition_matrices(transition_matricesSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type predictor_sets_rect(predictor_sets_rectSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_epred_state_prob_internal(n_samples, max_times, initial_states, n_states, n_time, n_predictor_sets, transition_matrices, predictor_sets_rect));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_covid19retrospective_rcppeigen_outerproduct", (DL_FUNC) &_covid19retrospective_rcppeigen_outerproduct, 1},
    {"_covid19retrospective_posterior_epred_state_prob_internal", (DL_FUNC) &_covid19retrospective_posterior_epred_state_prob_internal, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_covid19retrospective(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
